{% set name = "magpylib" %}
{% set version = "4.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 310d3ef51a50c09e6031ae14fd6213d96274efa42b0247acac898b3981f90125

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - matplotlib-base >=3.3
    - numpy >=1.20
    - scipy >=1.6
test:
  imports:
    - {{ name }}

about:
  home: http://github.com/magpylib/magpylib
  license: AGPL-3.0-or-later
  license_family: AGPL
  license_file: LICENSE
  summary: A simple, user friendly Python 3 toolbox for calculating magnetic fields from permanent magnets and current distributions.

  description: |
    magpylib provides simple and easy to use classes for calculating magnetic
    fields depending only on numpy and matplotlib. The core of the library is
    the source class which can represent permanent magnets, current
    distributions or magnetic moments in a 3D space. The library provides simple
    ways to generate such source objects, to manipulate them geometrically, to
    group several sources into a Collection system and to calculate the
    resulting fields of such systems. The systems may also be quickly visualized
    with a matplotlib based 3D plot method.
  doc_url: https://magpylib.readthedocs.io/en/latest/
  dev_url: https://github.com/magpylib/magpylib

extra:
  recipe-maintainers:
    - OrtnerMichael
    - lucasgcb
